name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adoptium@11
      - name: Checking your code format
        run: sbt scalafmtCheckAll headerCheck Test/headerCheck
      - name: Run compile
        run: sbt -v -J-Xmx6g +compile +test testsJS/run testsJVM/run
