name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v4
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v7
        with:
          java-version: adoptjdk@14
      - name: Checking your code format
        run: csbt scalafmtCheckAll headerCheck test:headerCheck
      - name: Run compile
        run: csbt +compile +test
